accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup',views.signup_view, name='signup'),
    path('login',views.login_view, name='login'),
    path('logout',views.logout_view, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('',views.articles_list, name="list"),
    path('create',views.create_article, name="create"),
    path('<slug>',views.article_detail, name= "detail"),
]

pjt1/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/' , views.about),
    path('' , include('articles.urls')),
    path('accounts/' , include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
     title = models.CharField(max_length = 100)
     slug = models.SlugField()
     body = models.TextField()
     date = models.DateTimeField(auto_now_add = True)
     image = models.ImageField(default='default.jpg',blank=True)
     author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)

     def __str__(self):
          return self.title

     def snippet(self):
          return self.body[:25] + ' ...'

articles/forms.py
from django import forms
from .models import Article

class CreateArticle(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','slug','body','image']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            #login
            user = form.save()
            login(request,user)

            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #login user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')


    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

def articles_list(request):
     articles = Article.objects.all().order_by('-date')
     return render(request, 'articles/articleslist.html',{'articles':articles})

def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html',{'article':article})

@login_required(login_url="/accounts/login")
def create_article(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            #save
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/create_article.html',{'form':form})

pjt1/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def about(request):
    return render(request , 'about.html')

def home(request):
    return render(request , 'home.html')

accounts/templates/accounts/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/all.css">
    <link rel="stylesheet" href="/static/fontawesome.css">
</head>
<body>
<header>
<h2 class="home"><a href="{% url 'articles:list' %}"><i class="fas fa-home home_icon"></i></a></h2>
<nav>
    <ul>
        {% if user.is_authenticated %}
        <li>
            <form action="{% url 'accounts:logout' %}" class="logout-link" method="post">
                {% csrf_token %}
                <button type="submit">logout<i class="fas fa-sign-out-alt out-icon"></i> </button>
            </form>
        </li>
        <li>
            <a class="highlight" href="{% url 'articles:create' %}"><b>create article </b><i class="fas fa-pencil-alt pen"></i></a>
        </li>
        {% else %}
        <li>
            <a href="{% url 'accounts:signup' %}" class="btnh">Sign up<i class="fas fa-user-plus btnhi"></i></a>
        </li>
        {%endif%}
    </ul>
</nav>
</header>
<div class="wrapper">
    <h1>login</h1><br>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {{form}}
        {% csrf_token %}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {%endif%}
        <input type="submit" value="login">
    </form>
</div>
</body>
</html>

accounts/templates/accounts/signup.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/all.css">
    <link rel="stylesheet" href="/static/fontawesome.css">
</head>
<body>
<header>
<h2 class="home"><a href="{% url 'articles:list' %}"><i class="fas fa-home home_icon"></i></a></h2>
<nav>
    <ul>
        {% if user.is_authenticated %}
        <li>
            <form action="{% url 'accounts:logout' %}" class="logout-link" method="post">
                {% csrf_token %}
                <button type="submit">logout<i class="fas fa-sign-out-alt out-icon"></i> </button>
            </form>
        </li>
        <li>
            <a class="highlight" href="{% url 'articles:create' %}"><b>create article </b><i class="fas fa-pencil-alt pen"></i></a>
        </li>
        {% else %}
        <li>
            <a href="{% url 'accounts:login' %}" class="btnh">Login<i class="fas fa-sign-in-alt btnhi"></i></a>
        </li>
        {%endif%}
    </ul>
</nav>
</header>
<div class="wrapper">
    <h1>sign up</h1>
    <form class="site-form" action="/accounts/signup" method="post">
        {{form}}
        {% csrf_token %}
        <input type="submit" value="signup">
    </form>
</div>
</body>
</html>

articles/templates/articles/Article_detail.html
{%extends 'base.html'%}
{% block title %}
    articles
{%endblock%}

{% block static %}
style.css
{%endblock%}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{article.image.url}}" alt="">
        <h1>{{article.title}}</h1>
        <br>
        <h3>{{article.body}}</h3>
        <br>
        <p>{{article.date}}</p>
    </div>
</div>
{%endblock%}

articles/templates/articles/articleslist.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/all.css">
    <link rel="stylesheet" href="/static/fontawesome.css">
</head>
<body>
<header>
<nav>
    <ul>
        {% if user.is_authenticated %}
        <li>
            <form action="{% url 'accounts:logout' %}" class="logout-link" method="post">
                {% csrf_token %}
                <button type="submit">logout<i class="fas fa-sign-out-alt out-icon"></i> </button>
            </form>
        </li>
        <li>
            <a class="highlight" href="{% url 'articles:create' %}"><b>create article </b><i class="fas fa-pencil-alt pen"></i></a>
        </li>
        {% else %}
        <li>
            <a href="{% url 'accounts:login' %}" class="btnh">Login<i class="fas fa-sign-in-alt btnhi"></i></a>
        </li>
        <li>
            <a href="{% url 'accounts:signup' %}" class="btnh">Sign up<i class="fas fa-user-plus btnhi"></i></a>
        </li>
        {%endif%}
    </ul>
</nav>
</header>
<div class="wrapper">
  <h1>Articles List</h1>
        <div class="articles">
            {% for article in articles %}
                <div class="article">
                    <img src="{{article.image.url}}" alt="" class="list-img">
                    <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
                    <p>{{article.snippet}}</p>
                    <p>{{article.date}}</p>
                    <p class="author">added by {{article.author.username}}</p>
                </div>
            {%endfor%}
        </div>

</div>
</body>
</html>

articles/templates/articles/create_article.html
{%extends 'base.html'%}
{% block title %}
    articles
{%endblock%}

{% block static %}
style.css
{%endblock%}

{% block content %}
    <div class="create_aticle">
        <h1>create your article!</h1>
        <form action="{% url 'articles:create' %}" class="site-form" method="post" enctype="multipart/form-data">
            {{form}}
            {% csrf_token %}
            <input type="submit" name="" value="create">
        </form>
    </div>
<script src="/static/slugify.js"></script>
{%endblock%}

templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>

<body>
    <h1>About</h1>
    <p>my name is sina firoozan</p>
</body>

</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            articles
        {%endblock%}
    </title>
    <link rel="stylesheet" href="/static/{% block static %}style.css{%endblock%}">
    <link rel="stylesheet" href="/static/all.css">
    <link rel="stylesheet" href="/static/fontawesome.css">
</head>
<body>
<header>
<h2 class="home"><a href="{% url 'articles:list' %}"><i class="fas fa-home home_icon"></i></a></h2>
<nav>
    <ul>
        {% if user.is_authenticated %}
        <li>
            <form action="{% url 'accounts:logout' %}" class="logout-link" method="post">
                {% csrf_token %}
                <button type="submit">logout<i class="fas fa-sign-out-alt out-icon"></i> </button>
            </form>
        </li>
        <li>
            <a class="highlight" href="{% url 'articles:create' %}"><b>create article </b><i class="fas fa-pencil-alt pen"></i></a>
        </li>
        {% else %}
        <li>
            <a href="{% url 'accounts:login' %}" class="btnh">Login<i class="fas fa-sign-in-alt btnhi"></i></a>
        </li>
        <li>
            <a href="{% url 'accounts:signup' %}" class="btnh">Sign up<i class="fas fa-user-plus btnhi"></i></a>
        </li>
        {%endif%}
    </ul>
</nav>
</header>
<div class="wrapper">
    {% block content %}
    {%endblock%}
</div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>

<body>
    <h1>Home</h1>
    <p>Welcome to my blog</p>
</body>

</html>